-- MySQL Script generated by MySQL Workbench
-- Qui 03 Set 2015 22:23:33 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema friendsPlay
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema friendsPlay
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `friendsPlay` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `friendsPlay` ;

-- -----------------------------------------------------
-- Table `friendsPlay`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendsPlay`.`usuario` (
  `id_usuario` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `friendsPlay`.`categoria_esportiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendsPlay`.`categoria_esportiva` (
  `idcategoria_esportiva` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `num_min` INT NOT NULL,
  `num_max` INT NOT NULL,
  PRIMARY KEY (`idcategoria_esportiva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `friendsPlay`.`local_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendsPlay`.`local_evento` (
  `idlocal_evento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `local` VARCHAR(100) NOT NULL,
  `numero` INT NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlocal_evento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `friendsPlay`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendsPlay`.`evento` (
  `idevento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `num_atual` INT NOT NULL,
  `privacidade` VARCHAR(20) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  `categoria_esportiva_idcategoria_esportiva` INT UNSIGNED NOT NULL,
  `local_evento_idlocal_evento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idevento`, `categoria_esportiva_idcategoria_esportiva`, `local_evento_idlocal_evento`),
  INDEX `fk_evento_categoria_esportiva1_idx` (`categoria_esportiva_idcategoria_esportiva` ASC),
  INDEX `fk_evento_local_evento1_idx` (`local_evento_idlocal_evento` ASC),
  CONSTRAINT `fk_evento_categoria_esportiva1`
    FOREIGN KEY (`categoria_esportiva_idcategoria_esportiva`)
    REFERENCES `friendsPlay`.`categoria_esportiva` (`idcategoria_esportiva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_local_evento1`
    FOREIGN KEY (`local_evento_idlocal_evento`)
    REFERENCES `friendsPlay`.`local_evento` (`idlocal_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `friendsPlay`.`convite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendsPlay`.`convite` (
  `idconvite` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `evento_idevento` INT UNSIGNED NOT NULL,
  `usuario_id_usuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idconvite`, `evento_idevento`, `usuario_id_usuario`),
  INDEX `fk_convite_evento1_idx` (`evento_idevento` ASC),
  INDEX `fk_convite_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_convite_evento1`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `friendsPlay`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_convite_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `friendsPlay`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
